=== mfulz/tmux-penmux/schemas/penmux-module-keytable.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="KeyType">
    <xs:sequence>
      <xs:element name="Key" type="xs:string" />
      <xs:element name="Func" type="xs:string" />
      <xs:element name="Description" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="PenmuxModuleKeytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="PrefixKey" type="xs:string" />
        <xs:element name="Key" type="KeyType" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mfulz/tmux-penmux/keytables/Session.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModuleKeytable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/penmux-module-keytable.xsd">
  <PrefixKey>s</PrefixKey>
  <Key>
    <Key>n</Key>
    <Func>new</Func>
    <Description>Creates a new session</Description>
  </Key>
  <Key>
    <Key>e</Key>
    <Func>exit</Func>
    <Description>Exits a session</Description>
  </Key>
  <Key>
    <Key>l</Key>
    <Func>load</Func>
    <Description>Loads a session from .pmses file</Description>
  </Key>
  <Key>
    <Key>s</Key>
    <Func>save</Func>
    <Description>Saves a session to .pmses file</Description>
  </Key>
</PenmuxModuleKeytable>
