=== mfulz/tmux-penmux/schemas/penmux-module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="OptionType">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="Description" type="xs:string" />
      <xs:element name="DefaultValue" type="xs:anySimpleType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="Mandatory"
    type="xs:boolean"
    use="optional" />
    <xs:attribute name="Private"
    type="xs:boolean"
    use="optional" />
  </xs:complexType>
  <xs:complexType name="OptionTypeString">
    <xs:complexContent>
      <xs:restriction base="OptionType">
        <xs:sequence>
          <xs:element name="Name" type="xs:string" />
          <xs:element name="Description" type="xs:string" />
          <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="Mandatory"
        type="xs:boolean"
        use="optional" />
        <xs:attribute name="Private"
        type="xs:boolean"
        use="optional" />
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="OptionTypeBool">
    <xs:complexContent>
      <xs:restriction base="OptionType">
        <xs:sequence>
          <xs:element name="Name" type="xs:string" />
          <xs:element name="Description" type="xs:string" />
          <xs:element name="DefaultValue" type="xs:boolean" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="Mandatory"
        type="xs:boolean"
        use="optional" />
        <xs:attribute name="Private"
        type="xs:boolean"
        use="optional" />
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>


  <xs:element name="PenmuxModule">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:string" />
        <xs:element name="Description" type="xs:string" />
        <xs:element name="Command" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="HandleScript" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="Use" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="Depend" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="Option" type="OptionType" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mfulz/tmux-penmux/modules/auxiliary/misc/commander.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../schemas/penmux-module.xsd">
  <Name>Commander</Name>
  <Description>Command launcher module that reads in csv files that have different commands predefined</Description>
  <HasRun>true</HasRun>
  <HandleScript>auxiliary/misc/commander/module.sh</HandleScript>
  <Option xsi:type="OptionTypeString" Private="true" Exported="true">
    <Name>CommandSearchPath</Name>
    <Description>Path that contains CSV files that holds the command definitions</Description>
    <DefaultValue>$HOME/.tmux/plugins/tmux-penmux/modules/auxiliary/misc/commander/commands</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeString">
    <Name>RemoteHost</Name>
    <Description>Defines the remote host(s)</Description>
    <DefaultValue>127.0.0.1</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeInt">
    <Name>RemotePort</Name>
    <Description>Defines the remote port</Description>
    <DefaultValue>80</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeString">
    <Name>LocalHost</Name>
    <Description>Defines the local host</Description>
    <DefaultValue>127.0.0.1</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeInt">
    <Name>LocalPort</Name>
    <Description>Defines the local port</Description>
    <DefaultValue>4444</DefaultValue>
  </Option>
  <Consumes NoNotify="true">
    <Name>SessionDir</Name>
    <Description>The final session directory. Can be used by other modules to store data.</Description>
  </Consumes>
</PenmuxModule>
