=== mfulz/tmux-penmux/schemas/penmux-module-options.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="OptionType">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="DefaultValue" type="xs:string" />
    </xs:sequence>
  </xs:complexType>

  <xs:element name="PenmuxModuleOptions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Option" type="OptionType" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mfulz/tmux-penmux/options/HttpExchange.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModuleOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/penmux-module-options.xsd">
  <Option>
    <Name>CommandSearchPath</Name>
    <DefaultValue>$HOME/.tmux/plugins/tmux-penmux/modules/auxiliary/comm/httpexchange/commands</DefaultValue>
  </Option>
  <Option>
    <Name>NoConfirm</Name>
    <DefaultValue>false</DefaultValue>
  </Option>
  <Option>
    <Name>HttpHost</Name>
    <DefaultValue>127.0.0.1</DefaultValue>
  </Option>
  <Option>
    <Name>HttpPort</Name>
    <DefaultValue>8080</DefaultValue>
  </Option>
  <Option>
    <Name>UseSessionDir</Name>
    <DefaultValue>true</DefaultValue>
  </Option>
  <Option>
    <Name>HttpRootDirBase</Name>
    <DefaultValue>$HOME/.tmux/penmux/httpexchange/#S/</DefaultValue>
  </Option>
  <Option>
    <Name>LocalPort</Name>
    <DefaultValue>4444</DefaultValue>
  </Option>
  <Option>
    <Name>LocalTempPort</Name>
    <DefaultValue>8800</DefaultValue>
  </Option>
</PenmuxModuleOptions>

=== mfulz/tmux-penmux/options/msfvenom.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModuleOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/penmux-module-options.xsd">
  <Option>
    <Name>Payload</Name>
    <DefaultValue>generic/shell_reverse_tcp</DefaultValue>
  </Option>
  <Option>
    <Name>Arch</Name>
    <DefaultValue>x64</DefaultValue>
  </Option>
  <Option>
    <Name>Platform</Name>
    <DefaultValue>windows</DefaultValue>
  </Option>
  <Option>
    <Name>Format</Name>
    <DefaultValue>exe</DefaultValue>
  </Option>
  <Option>
    <Name>NoConfirm</Name>
    <DefaultValue>true</DefaultValue>
  </Option>
  <Option>
    <Name>SubPath</Name>
    <DefaultValue>###LocalHost###-###LocalPort###</DefaultValue>
  </Option>
  <Option>
    <Name>LocalHost</Name>
    <DefaultValue>127.0.0.1</DefaultValue>
  </Option>
  <Option>
    <Name>LocalPort</Name>
    <DefaultValue>4444</DefaultValue>
  </Option>
  <Option>
    <Name>CacheDir</Name>
    <DefaultValue>$HOME/.tmux/penmux/.msfvenom/cache</DefaultValue>
  </Option>
</PenmuxModuleOptions>

=== mfulz/tmux-penmux/options/Snipper.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModuleOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/penmux-module-options.xsd">
  <Option>
    <Name>SnippetSearchPath</Name>
    <DefaultValue>$HOME/.tmux/plugins/tmux-penmux/modules/auxiliary/Snipper/snippets</DefaultValue>
  </Option>
  <Option>
    <Name>ClipboardCommand</Name>
    <DefaultValue>echo '$$snippet$$' | xclip -i -sel c</DefaultValue>
  </Option>
  <Option>
    <Name>LocalHost</Name>
    <DefaultValue>127.0.0.1</DefaultValue>
  </Option>
  <Option>
    <Name>LocalPort</Name>
    <DefaultValue>4444</DefaultValue>
  </Option>
</PenmuxModuleOptions>

=== mfulz/tmux-penmux/options/Commander.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModuleOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/penmux-module-options.xsd">
  <Option>
    <Name>CommandSearchPath</Name>
    <DefaultValue>$HOME/.tmux/plugins/tmux-penmux/modules/auxiliary/Commander/commands</DefaultValue>
  </Option>
  <Option>
    <Name>NoConfirm</Name>
    <DefaultValue>false</DefaultValue>
  </Option>
  <Option>
    <Name>RemoteHost</Name>
    <DefaultValue>127.0.0.1</DefaultValue>
  </Option>
  <Option>
    <Name>RemotePort</Name>
    <DefaultValue>80</DefaultValue>
  </Option>
  <Option>
    <Name>RemoteProto</Name>
    <DefaultValue>http</DefaultValue>
  </Option>
  <Option>
    <Name>LocalHost</Name>
    <DefaultValue>127.0.0.1</DefaultValue>
  </Option>
  <Option>
    <Name>LocalPort</Name>
    <DefaultValue>4444</DefaultValue>
  </Option>
  <Option>
    <Name>LocalTempPort</Name>
    <DefaultValue>8800</DefaultValue>
  </Option>
</PenmuxModuleOptions>

=== mfulz/tmux-penmux/options/Session.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModuleOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/penmux-module-options.xsd">
  <Option>
    <Name>AutoLoad</Name>
    <DefaultValue>true</DefaultValue>
  </Option>
  <Option>
    <Name>AutoSave</Name>
    <DefaultValue>true</DefaultValue>
  </Option>
  <Option>
    <Name>NoConfirm</Name>
    <DefaultValue>false</DefaultValue>
  </Option>
  <Option>
    <Name>UseCwd</Name>
    <DefaultValue>true</DefaultValue>
  </Option>
  <Option>
    <Name>SessionDirBase</Name>
    <DefaultValue>$HOME/.tmux/penmux/sessions</DefaultValue>
  </Option>
</PenmuxModuleOptions>

=== mfulz/tmux-penmux/options/ScriptLog.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModuleOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/penmux-module-options.xsd">
  <Option>
    <Name>LogExisting</Name>
    <DefaultValue>true</DefaultValue>
  </Option>
  <Option>
    <Name>Name</Name>
    <DefaultValue>%Y%m%d-#T-(#D).log</DefaultValue>
  </Option>
  <Option>
    <Name>LogPenmuxSessionDir</Name>
    <DefaultValue>true</DefaultValue>
  </Option>
  <Option>
    <Name>LogDir</Name>
    <DefaultValue>$HOME/.tmux/penmux/scriptlog/#S</DefaultValue>
  </Option>
</PenmuxModuleOptions>
