=== mfulz/tmux-penmux/schemas/penmux-module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="OptionType">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="Description" type="xs:string" />
      <xs:element name="DefaultValue" type="xs:anySimpleType" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="Mandatory"
    type="xs:boolean"
    use="optional" />
    <xs:attribute name="Private"
    type="xs:boolean"
    use="optional" />
  </xs:complexType>
  <xs:complexType name="OptionTypeString">
    <xs:complexContent>
      <xs:restriction base="OptionType">
        <xs:sequence>
          <xs:element name="Name" type="xs:string" />
          <xs:element name="Description" type="xs:string" />
          <xs:element name="DefaultValue" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="Mandatory"
        type="xs:boolean"
        use="optional" />
        <xs:attribute name="Private"
        type="xs:boolean"
        use="optional" />
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="OptionTypeBool">
    <xs:complexContent>
      <xs:restriction base="OptionType">
        <xs:sequence>
          <xs:element name="Name" type="xs:string" />
          <xs:element name="Description" type="xs:string" />
          <xs:element name="DefaultValue" type="xs:boolean" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="Mandatory"
        type="xs:boolean"
        use="optional" />
        <xs:attribute name="Private"
        type="xs:boolean"
        use="optional" />
      </xs:restriction>
    </xs:complexContent>
  </xs:complexType>


  <xs:element name="PenmuxModule">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:string" />
        <xs:element name="Description" type="xs:string" />
        <xs:element name="Command" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="HandleScript" type="xs:string" minOccurs="0" maxOccurs="1" />
        <xs:element name="Use" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="Depend" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        <xs:element name="Option" type="OptionType" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mfulz/tmux-penmux/modules/payloads/msfvenom.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/penmux-module.xsd">
  <Name>msfvenom</Name>
  <Description>Module to assist creating payloads by using msfvenom</Description>
  <HasRun>true</HasRun>
  <Option xsi:type="OptionTypeSelection" Private="true" Exported="true">
    <Name>Payload</Name>
    <Description>Payload to use (msfvenom -l payloads)</Description>
  </Option>
  <Option xsi:type="OptionTypeSelection" Private="true" Exported="true">
    <Name>Arch</Name>
    <Description>Architecture to target (msfvenom -l archs)</Description>
  </Option>
  <Option xsi:type="OptionTypeSelection" Private="true" Exported="true">
    <Name>Platform</Name>
    <Description>Platform to target (msfvenom -l platforms)</Description>
  </Option>
  <Option xsi:type="OptionTypeSelection" Private="true" Exported="true">
    <Name>Format</Name>
    <Description>Format to use (msfvenom -l formats)</Description>
  </Option>
  <Option xsi:type="OptionTypeSelection" Private="true" Exported="true">
    <Name>Encoder</Name>
    <Description>Encoder to use (msfvenom -l encoders)</Description>
  </Option>
  <Option xsi:type="OptionTypeBool" Private="true" Exported="true">
    <Name>NoConfirm</Name>
    <Description>Start the command after selection. When enabled you can't edit the command before running</Description>
  </Option>
  <Option xsi:type="OptionTypeString">
    <Name>SubPath</Name>
    <Description>Use this path to store generated payloads. Default is LocalHost-LocalPort/</Description>
  </Option>
  <Option xsi:type="OptionTypeString">
    <Name>LocalHost</Name>
    <Description>Defines the local host</Description>
  </Option>
  <Option xsi:type="OptionTypeInt">
    <Name>LocalPort</Name>
    <Description>Defines the local port</Description>
  </Option>
  <Option xsi:type="OptionTypeString">
    <Name>CacheDir</Name>
    <Description>This directory is used to create cache files for the different msfvenom argument lists (payloads, encoders, etc)</Description>
  </Option>
  <Consumes NoNotify="true">
    <Name>SessionDir</Name>
    <From>Session</From>
  </Consumes>
  <Consumes NoNotify="true">
    <Name>HttpRootDir</Name>
    <From>HttpExchange</From>
  </Consumes>
</PenmuxModule>

=== mfulz/tmux-penmux/modules/auxiliary/Snipper.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/penmux-module.xsd">
  <Name>Snipper</Name>
  <Description>Snipper module that reads in csv files that have different useful snippets. Will be copied into clipboard</Description>
  <HasRun>true</HasRun>
  <Option xsi:type="OptionTypeString" Private="true" Exported="true">
    <Name>SnippetSearchPath</Name>
    <Description>Path that contains CSV files that holds the snippets</Description>
  </Option>
  <Option xsi:type="OptionTypeString" Private="true" Exported="true">
    <Name>ClipboardCommand</Name>
    <Description>Command used for copying snippet to clipboard</Description>
  </Option>
  <Option xsi:type="OptionTypeString">
    <Name>LocalHost</Name>
    <Description>Defines the local host</Description>
  </Option>
  <Option xsi:type="OptionTypeInt">
    <Name>LocalPort</Name>
    <Description>Defines the local port</Description>
  </Option>
  <Consumes NoNotify="true">
    <Name>HttpUri</Name>
    <From>HttpExchange</From>
  </Consumes>
</PenmuxModule>

=== mfulz/tmux-penmux/modules/auxiliary/session.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/penmux-module.xsd">
  <Name>Session</Name>
  <Description>Module to persist penmux sessions and provide easy to use storage of module options</Description>
  <CmdPrio>100</CmdPrio>
  <NotifyOptions>true</NotifyOptions>
  <Option xsi:type="OptionTypeBool" Private="true" Exported="true">
    <Name>AutoLoad</Name>
    <Description>If enabled sessions will be loaded automatically after cd into a directory that includes a session file</Description>
  </Option>
  <Option xsi:type="OptionTypeBool" Private="true" Exported="true">
    <Name>AutoSave</Name>
    <Description>If enabled sessions will be saved automatically after change of module options</Description>
  </Option>
  <Option xsi:type="OptionTypeBool" Private="true" Exported="true">
    <Name>NoConfirm</Name>
    <Description>If enabled creating a new session that points to a existing one will overwrite the session file without confirmation</Description>
  </Option>
  <Option xsi:type="OptionTypeBool" Private="true" Exported="true">
    <Name>UseCwd</Name>
    <Description>If enabled new session will be created as sub directory to the current dir</Description>
  </Option>
  <Option xsi:type="OptionTypeString" Private="true" Exported="true">
    <Name>SessionDirBase</Name>
    <Description>Default directory to use for sessions. Has no effect when UseCwd is set to true.</Description>
  </Option>
  <Option xsi:type="OptionTypeString" Provided="true">
    <Name>SessionName</Name>
    <Description>Session name.</Description>
  </Option>
  <Option xsi:type="OptionTypeString" Provided="true">
    <Name>SessionDir</Name>
    <Description>Final Session directory.</Description>
  </Option>
</PenmuxModule>

=== mfulz/tmux-penmux/modules/auxiliary/misc/session.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../schemas/penmux-module.xsd">
  <Name>Session</Name>
  <Description>Module to persist penmux sessions and provide easy to use storage of module options</Description>
  <HandleScript>auxiliary/misc/session/module.sh</HandleScript>
  <Option xsi:type="OptionTypeBool" Private="true">
    <Name>AutoLoad</Name>
    <Description>If enabled sessions will be loaded automatically after cd into a directory that includes a session file</Description>
    <DefaultValue>true</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeBool" Private="true">
    <Name>UseCwd</Name>
    <Description>If enabled new session will be created as sub directory to the current dir</Description>
    <DefaultValue>true</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeString" Private="true">
    <Name>SessionDir</Name>
    <Description>Default directory to use for sessions. Has no effect when UseCwd is set to true.</Description>
    <DefaultValue>$HOME/.tmux/penmux/sessions</DefaultValue>
  </Option>
</PenmuxModule>

=== mfulz/tmux-penmux/modules/auxiliary/misc/snipper.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../schemas/penmux-module.xsd">
  <Name>Snipper</Name>
  <Description>Snipper module that reads in csv files that have different useful snippets. Will be copied into clipboard</Description>
  <HasRun>true</HasRun>
  <HandleScript>auxiliary/misc/snipper/module.sh</HandleScript>
  <Option xsi:type="OptionTypeString" Private="true" Exported="true">
    <Name>SnippetSearchPath</Name>
    <Description>Path that contains CSV files that holds the snippets</Description>
    <DefaultValue>$HOME/.tmux/plugins/tmux-penmux/modules/auxiliary/misc/snipper/snippets</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeString" Private="true" Exported="true">
    <Name>ClipboardCommand</Name>
    <Description>Command used for copying snippet to clipboard</Description>
    <DefaultValue>echo $$snippet$$ | xclip -i -sel c</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeString">
    <Name>LocalHost</Name>
    <Description>Defines the local host</Description>
    <DefaultValue>127.0.0.1</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeInt">
    <Name>LocalPort</Name>
    <Description>Defines the local port</Description>
    <DefaultValue>4444</DefaultValue>
  </Option>
  <Consumes NoNotify="true">
    <Name>HttpUri</Name>
    <Description>Provides the final http server base uri. Can be used by other modules to store files</Description>
  </Consumes>
</PenmuxModule>

=== mfulz/tmux-penmux/modules/auxiliary/reporting/scriptlog.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../schemas/penmux-module.xsd">
  <Name>ScriptLog</Name>
  <Description>Module to log terminal input / output to files (using util/linux script)</Description>
  <CmdPrio>200</CmdPrio>
  <HandleScript>auxiliary/reporting/scriptlog/module.sh</HandleScript>
  <Option xsi:type="OptionTypeBool" Private="true">
    <Name>LogExisting</Name>
    <Description>If enabled all existing panes will start logging</Description>
    <DefaultValue>true</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeString" Private="true">
    <Name>Name</Name>
    <Description>Logfile name to use. All tmux placeholders can be used (ae. #W, #S, etc.)</Description>
    <DefaultValue>%Y%m%d-#T-(#D).log</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeBool" Private="true">
    <Name>LogPenmuxSessionDir</Name>
    <Description>Log to penmux session directory if set. If not set use LogDir</Description>
    <DefaultValue>true</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeString" Private="true">
    <Name>LogDir</Name>
    <Description>Directory to store logfiles. All tmux placeholders can be used (ae. #W, #S, etc.)</Description>
    <DefaultValue>$HOME/.tmux/penmux/logs/#S</DefaultValue>
  </Option>
  <Consumes>
    <Name>SessionDir</Name>
    <Description>The final session directory. Can be used by other modules to store data.</Description>
  </Consumes>
</PenmuxModule>

=== mfulz/tmux-penmux/modules/auxiliary/commander.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/penmux-module.xsd">
  <Name>Commander</Name>
  <Description>Command launcher module that reads in csv files that have different commands predefined</Description>
  <HasRun>true</HasRun>
  <HandleScript>auxiliary/commander/module.sh</HandleScript>
  <Option xsi:type="OptionTypeString" Private="true" Exported="true">
    <Name>CommandSearchPath</Name>
    <Description>Path that contains CSV files that holds the command definitions</Description>
  </Option>
  <Option xsi:type="OptionTypeBool" Private="true" Exported="true">
    <Name>NoConfirm</Name>
    <Description>Start the command after selection. When enabled you can't edit the command before running</Description>
  </Option>
  <Option xsi:type="OptionTypeString">
    <Name>RemoteHost</Name>
    <Description>Defines the remote host(s)</Description>
  </Option>
  <Option xsi:type="OptionTypeInt">
    <Name>RemotePort</Name>
    <Description>Defines the remote port</Description>
  </Option>
  <Option xsi:type="OptionTypeString">
    <Name>RemoteProto</Name>
    <Description>Defines the default remote protocol</Description>
  </Option>
  <Option xsi:type="OptionTypeString">
    <Name>LocalHost</Name>
    <Description>Defines the local host</Description>
  </Option>
  <Option xsi:type="OptionTypeInt">
    <Name>LocalPort</Name>
    <Description>Defines the local port</Description>
  </Option>
  <Option xsi:type="OptionTypeInt" Private="true" Exported="true">
    <Name>LocalTempPort</Name>
    <Description>Defines a local port to be used for temporary internal tasks</Description>
  </Option>
   <Consumes NoNotify="true">
    <Name>SessionDir</Name>
    <Description>The final session directory. Can be used by other modules to store data.</Description>
  </Consumes>
  <Consumes NoNotify="true">
    <Name>HttpRootDir</Name>
    <Description>Provides the final http server root directory which holds the files. Can be used by other modules to store files</Description>
  </Consumes>
</PenmuxModule>

=== mfulz/tmux-penmux/modules/comm/httpexchange.xml
<?xml version="1.0" encoding="UTF-8"?>
<PenmuxModule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../schemas/penmux-module.xsd">
  <Name>HttpExchange</Name>
  <Description>HTTP server module that enables easy file downloading to targets</Description>
  <HasRun>true</HasRun>
  <HandleScript>auxiliary/comm/httpexchange/module.sh</HandleScript>
  <Option xsi:type="OptionTypeString" Private="true" Exported="true">
    <Name>CommandSearchPath</Name>
    <Description>Path that contains CSV files that holds the download command definitions</Description>
    <DefaultValue>$HOME/.tmux/plugins/tmux-penmux/modules/auxiliary/comm/httpexchange/commands</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeBool" Private="true" Exported="true">
    <Name>NoConfirm</Name>
    <Description>Start the download command after selection. When enabled you can't edit the command before running</Description>
    <DefaultValue>false</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeString" Private="true" Exported="true">
    <Name>HttpHost</Name>
    <Description>Defines the local host</Description>
    <DefaultValue>127.0.0.1</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeInt" Private="true" Exported="true">
    <Name>HttpPort</Name>
    <Description>Defines the local port</Description>
    <DefaultValue>8080</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeBool" Private="true" Exported="true">
    <Name>UseSessionDir</Name>
    <Description>Use session directory as base dir if set. If not set use HttpRootDirBaseDir</Description>
    <DefaultValue>true</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeString" Private="true" Exported="true">
    <Name>HttpRootDirBase</Name>
    <Description>Base directory to store http. All tmux placeholders can be used (ae. #W, #S, etc.)</Description>
    <DefaultValue>$HOME/.tmux/penmux/httpexchange/#S/</DefaultValue>
  </Option>
  <Option xsi:type="OptionTypeBool" Private="true" Exported="true" Volatile="true">
    <Name>HttpRunning</Name>
    <Description>Status to know that the server is running</Description>
  </Option>
  <Option xsi:type="OptionTypeString" Provided="true">
    <Name>HttpRootDir</Name>
    <Description>Provides the final http server root directory which holds the files. Can be used by other modules to store files</Description>
  </Option>
  <Option xsi:type="OptionTypeString" Provided="true" Volatile="true">
    <Name>HttpUri</Name>
    <Description>Provides the final http server base uri. Can be used by other modules to store files</Description>
  </Option>
  <Consumes NoNotify="true">
    <Name>SessionDir</Name>
    <Description>The final session directory. Can be used by other modules to store data.</Description>
  </Consumes>
</PenmuxModule>
